[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_list_web3 = "Hhjxz1vbt4hVsq4bxRg6LtcmmP2PoAwFPvyUhPL6sJKd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nikitayeubinh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
