[package]
name = "todo-list-web3"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "todo_list_web3"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = {version="0.26.0", features = ["init-if-needed"]}
anchor-spl = "0.26.0"
mpl-token-metadata = {version="1.9.0", features = ["no-entrypoint"]}
